from dataclasses import dataclass
from typing import Optional


@dataclass
class Subject:
    id: Optional[int]
    name: str
    color: str
    notes: str
    created_at: str
    sort_order: int = 0
    is_archived: int = 0


@dataclass
class TodoTask:
    """A Goal (shown in the UI as "Goals"). Kept the table/class name ``todo_tasks``
    / ``TodoTask`` to avoid a risky rename. ``name`` is the goal title, ``notes`` is
    the description/motivation. Outcome-focused, manually completed — never
    auto-completed from tracked time. May own milestones and may be generated by a
    recurring template (``template_id``)."""

    id: Optional[int]
    name: str
    notes: str
    deadline: Optional[str]
    is_completed: int
    sort_order: int
    created_at: str
    template_id: Optional[int] = None
    # Weekly focus: the user highlights goals they are concentrating on now.
    # Purely visual emphasis + manual toggle; never affects completion rules.
    is_focused: int = 0


@dataclass
class Milestone:
    id: Optional[int]
    goal_id: int
    title: str
    note: str
    is_done: int
    sort_order: int
    created_at: str


@dataclass
class GoalTemplate:
    """A recurring template that appends a normal Goal instance to the top of the
    list once per logical period (daily/weekly/monthly). Milestones to copy are
    stored as JSON. ``last_generated`` is the logical-period key last produced."""

    id: Optional[int]
    title: str
    notes: str
    recurrence: str          # 'daily' | 'weekly' | 'monthly'
    recurrence_day: Optional[int]  # weekly: ISO weekday 1-7; monthly: day 1-31
    milestones_json: str     # JSON list of {"title", "note"}
    last_generated: Optional[str]
    is_active: int
    sort_order: int
    created_at: str


@dataclass
class Session:
    id: Optional[int]
    task_id: int
    start_time: str
    end_time: Optional[str]
    duration_seconds: int
    # Sessions have no note field: it was removed from the schema (subjects and
    # milestones keep theirs). Don't reintroduce one without a migration.
    # Last time the app confirmed this session was still legitimately running.
    # Heartbeated ~once per minute while active; used by future crash/ghost-time
    # recovery. None for historical rows and for imported backups.
    last_active_at: Optional[str] = None

    @property
    def subject_id(self) -> int:
        """Semantic alias for task_id used by newer subject-oriented code paths."""
        return self.task_id
